const WIDTH = 900, HEIGHT = 600;
const GRAVITY = 0.7;
const FRICTION = 0.7;
const GROUND = HEIGHT - 60;
const PLATFORM_HEIGHT = 20;
const PLAYER_SIZE = 50;
const PLAYER_SPEED = 5;
const DASH_SPEED = 13;
const DASH_WINDOW = 250;
const JUMP_VEL = 15;
const MAX_JUMPS = 2;
const PLAYER_HP = 120;
const PLATFORM_COLOR = "#ffd54f";
const PLATFORM_EDGE = "#ffb300";
const PLAYER_OUTLINE = "#fff";
const FLOOR_HEIGHT = HEIGHT-30;
const DASH_COOLDOWN = 36;
const DASH_FRAMES = 8;
const DASH_DAMAGE = 22;
const SLOW_FALL_MULTIPLIER = 0.16;
const BLOCK_MAX = 100;
const BLOCK_DEPLETION = 1.8;
const BLOCK_RECOVERY = 0.8;
const DIZZY_FRAMES = 38;
const DIZZY_KNOCKBACK_X = 16, DIZZY_KNOCKBACK_Y = -9;
const BLOCK_PUSHBACK_X = 9, BLOCK_PUSHBACK_Y = -4;

